###
POST http://localhost:8010/recipes/
Content-Type: application/json

{
  "name": "6010 Alloy",
  "ingredients": [
    {
      "name": "aluminum"
    },{
      "name": "silicon"
    },{
      "name": "magnesium"
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8010/recipes/

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "{\"6010-alloy\":{\"name\":\"6010 Alloy\",\"ingredients\":[{\"name\":\"aluminum\"},{\"name\":\"silicon\"},{\"name\":\"magnesium\"}]}}", "Body match expected response")
    });
%}

###
GET http://localhost:8010/recipes/6010-alloy

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "{\"name\":\"6010 Alloy\",\"ingredients\":[{\"name\":\"aluminum\"},{\"name\":\"silicon\"},{\"name\":\"magnesium\"}]}", "Body match expected response")
    });
%}

###
PUT  http://localhost:8010/recipes/6010-alloy
Content-Type: application/json

{
  "name": "6010 Alloy",
  "ingredients": [
    {
      "name": "aluminum"
    },{
      "name": "silicon"
    },{
      "name": "magnesium"
    },{
      "name": "copper"
    }
  ]
}

> {%
    client.test("Request executed successfully", function() {

        client.log(response.body);
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8010/recipes/6010-alloy

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "{\"name\":\"6010 Alloy\",\"ingredients\":[{\"name\":\"aluminum\"},{\"name\":\"silicon\"},{\"name\":\"magnesium\"},{\"name\":\"copper\"}]}", "Body match expected response")

    });
%}

###
DELETE http://localhost:8010/recipes/6010-alloy

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8010/recipes/6010-alloy

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}