###
POST http://localhost:8010/users/
Content-Type: application/json

{
  "name": "Jackson Charvel",
  "email": "guitardude@gmail.com"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8010/users/

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "{\"jackson-charvel\":" +
            "{\"name\":\"Jackson Charvel\",\"email\":\"guitardude@gmail.com\"}}",
            "Body match expected response")
    });
%}

###
GET http://localhost:8010/users/jackson-charvel

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "{\"name\":\"Jackson Charvel\",\"email\":\"guitardude@gmail.com\"}",
            "Body match expected response")
    });
%}

###
PUT  http://localhost:8010/users/jackson-charvel
Content-Type: application/json

{
  "name": "Jackson Charvel",
  "email": "guitardude@willtomasini.com"
}

> {%
    client.test("Request executed successfully", function() {

        client.log(response.body);
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8010/users/jackson-charvel

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "{\"name\":\"Jackson Charvel\",\"email\":\"guitardude@willtomasini.com\"}",
            "Body match expected response")

    });
%}

###
DELETE http://localhost:8010/users/jackson-charvel

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8010/users/jackson-charvel

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}

###
POST http://localhost:8010/groups/
Content-Type: application/json

{
  "name": "Cool Kids",
  "id": 0
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8010/groups/

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "{\"cool-kids\":" +
            "{\"name\":\"Cool Kids\",\"id\":0}}",
            "Body match expected response")
    });
%}

###
GET http://localhost:8010/groups/cool-kids

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "{\"name\":\"Cool Kids\",\"id\":0}",
            "Body match expected response")
    });
%}

###
PUT http://localhost:8010/groups/cool-kids
Content-Type: application/json

{
  "name": "Cool Kids",
  "id": 1
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8010/groups/cool-kids

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === "{\"name\":\"Cool Kids\",\"id\":1}",
            "Body match expected response")
    });
%}

###
DELETE http://localhost:8010/users/cool-kids

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8010/users/cool-kids

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}